# -*- coding: utf-8 -*-
"""t-test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18gB4ueVukY_VCeB7E3oSLqu06MlkHgTS
"""



from scipy.stats import ttest_rel
import numpy as np

def paired_t_test_metric(metric_esn, metric_lstm, metric_name="Sharpe Ratio"):
    t_stat, p_value = ttest_rel(metric_lstm, metric_esn)  # LSTM - ESN

    print(f"📊 Paired t-test ({metric_name})")
    print(f" - Mean {metric_name} (LSTM): {np.mean(metric_lstm):.4f}")
    print(f" - Mean {metric_name} (ESN) : {np.mean(metric_esn):.4f}")
    print(f" - t-statistic: {t_stat:.4f}")
    print(f" - p-value    : {p_value:.4f}")

    if p_value < 0.05:
        better = "LSTM" if np.mean(metric_lstm) > np.mean(metric_esn) else "ESN"
        print(f"✅ 유의미한 차이 존재 → {better} 모델이 {metric_name} 기준으로 우수합니다.\n")
    else:
        print("⚖️  통계적으로 유의미한 차이를 발견하지 못했습니다.\n")

# 샤프지수 비교
paired_t_test_metric(sharpe_esn_list, sharpe_lstm_list, metric_name="Sharpe Ratio")

# MDD는 절댓값이 작을수록 좋으므로 음수이지만 비교 방식은 동일
paired_t_test_metric(mdd_esn_list, mdd_lstm_list, metric_name="MDD")